# Generated by Django 3.2.6 on 2021-08-17 01:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_1', models.CharField(default='', max_length=30)),
                ('product_2', models.CharField(default='', max_length=30)),
                ('product_3', models.CharField(default='', max_length=30)),
                ('product_4', models.CharField(default='', max_length=30)),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
