# Generated by Django 3.2.6 on 2021-08-17 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='product_1',
            new_name='product_name_1',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='product_2',
            new_name='product_name_2',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='product_3',
            new_name='product_name_3',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='product_4',
            new_name='product_name_4',
        ),
    ]
