# Generated by Django 3.2.6 on 2021-08-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210817_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='product_name_3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='product_name_4',
        ),
    ]
